import React from 'react';
export const metadata = {
    title: "Add-Product | Dashboard | Next Hero",
    description: "Generated by create next app",
  };
const AddProductPage = () => {
    return (
        <div>
            AddProductPage
        </div>
    );
};

export default AddProductPage;