import React from 'react';

export const metadata = {
    title: "About | Next Hero",
    description: "Generated by create next app",
  };

const AboutPage = () => {
    return (
        <div>
            About page
        </div>
    );
};

export default AboutPage;