

import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Hero",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  console.log("from root layout");
  return (
    <html lang="en">
      <body className={inter.className}>
        
        {children}

        </body>
    </html>
  );
};

export default RootLayout;
