
import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Hero",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  console.log("from root layout");
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex gap-4">
          <Link href='/'>Home</Link> 
          <Link href='/about'>About</Link> 
          <Link href='/dashboard'>Dashboard</Link> 
        </nav>
        {children}
        <footer>Footer</footer>
        </body>
    </html>
  );
};

export default RootLayout;
