import React from 'react';
export const metadata = {
    title: "Profile | Next Hero",
    description: "Generated by create next app",
  };

const ProfilePage = () => {
    return (
        <div>
            Profile Page
        </div>
    );
};

export default ProfilePage;