import React from 'react';
export const metadata = {
    title: "Dashboard | Next Hero",
    description: "Generated by create next app",
  };
const DashboardLayout = ({children}) => {
    return (
        <div>
            <h3>Left Side Bar</h3>
            {children}
        </div>
    );
};

export default DashboardLayout;